apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    # target the pod, not deployment
    app: nginx-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000